config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  get 'profil', to: 'profil#profil'
  resources :items
  resources :item_adds
  root 'index#index'
  get 'upload', to: 'index#upload', as: 'upload'
  get 'cart', to: 'index#cart', as: 'cart'
  post '/panier/remove/:id', to: "index#rm_from_cart", as: :remove
  get '/panier/remove/:id', to: "index#rm_from_cart", as: :removed
  post '/panier/:id', to: "index#add_to_cart", as: :adding
  devise_for :users

  resources :carts, only: [:new]
  get 'show', to: 'carts#show', as: 'pay'
  resources :charges

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bridge.rb
class Bridge < ApplicationRecord
  	belongs_to :cart
  	belongs_to :item
end

app/models/cart.rb
class Cart < ApplicationRecord

	has_many :bridges
	has_many :items, through: :bridges
	has_one :user
end

app/models/command.rb
class Command < ApplicationRecord
	belongs_to :user
	has_many :command_items
	has_many :items, through: :command_items
end

app/models/command_item.rb
class CommandItem < ApplicationRecord
	belongs_to :command
	belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :bridges
	has_many :carts, through: :bridges
	has_many :command_items 
	has_many :commands, through: :command_items
	has_one_attached :image
end

app/models/item_add.rb
class ItemAdd < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord

	has_one :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :cart
  has_many :commands

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def new

  end



  def show

    item = current_user.cart.items.all
    # Récupérer ts les items dans le panier du current user
  end

  def add_item_to_order
    ord = Order.new
    ord.user = current_user
    ord.save
    com = Command.new
    com.user = current_user

    current_user.cart.items.each do | item |
      com.items << item
      OrderMailer.with(order: @order).user_order_mailer.deliver_now
      OrderMailer.with(order: @order).admin_order_mailer.deliver_now
    end
    com.save
    current_user.cart.items.clear

    redirect_to root_path
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :authenticate_user!, only: [:cart]
  def index

    @items = Item.all

  end

  def cart
  end

  def add_to_cart
    if current_user.cart == nil
      current_user.create_cart
    end
    item = Item.find(params[:id])
    current_user.cart.items << item
    p current_user.cart.items
    puts '__________________'
    sleep 0.4 
    redirect_to root_path
  end 

  def rm_from_cart

    item_id = params[:id]
    cart_id = current_user.cart.id
    bridge = Bridge.where("cart_id == #{cart_id} AND item_id == #{item_id} ").first
    bridge.destroy
    redirect_to root_path

  end 

  def rm_from_cart_page

    item_id = params[:id]
    cart_id = current_user.cart.id
    bridge = Bridge.where("cart_id == #{cart_id} AND item_id == #{item_id} ").first
    bridge.destroy
    redirect_to root_path

  end 

  def upload
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/item_adds_helper.rb
module ItemAddsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/views/index/cart.html.erb

	<%= render 'layouts/navbar'%>
	<!-- Title Page -->
	<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url(images/banner-chat-5.jpg);">
		<h2 class="l-text2 t-center">
			Panier
		</h2>
	</section>
	<!-- Cart -->
	<section class="cart bgwhite p-t-70 p-b-100">
		<div class="container">

			<!-- Cart item -->
			<div class="container-table-cart pos-relative">
				<div class="wrap-table-shopping-cart bgwhite">
					<table class="table-shopping-cart">
						<tr class="table-head">
							<th class="column-1"></th>
							<th class="column-2">Produit</th>
							<th class="column-3">Prix</th>
							<th class="column-4 p-l-70">Quantité</th>
							<th class="column-5">Total</th>
						</tr>
					<%if user_signed_in? && current_user.cart != nil %>
						<% total =0 %>
							<% current_user.cart.items.each do |item| %>
								<tr class="table-row">
									<td class="column-1">
										<div class="cart-img-product b-rad-4 o-f-hidden">
											<%if item.image_url != nil %>
													<%= image_tag('cats/' + item.image_url) %>  
												<%else%>
													<%= image_tag item.image%>
												<%end%>
										</div>
									</td>
									<td class="column-2"><%= item.title %></td>
									<td class="column-3"> <%= item.price %>€</td>
									<td class="column-4">
										<div class="flex-w bo5 of-hidden w-size17">
										<!--ENLEVE QUANTITE
											<button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
												<i class="fs-12 fa fa-minus" aria-hidden="true"></i>
											</button>-->
											<input class="size8 m-text18 t-center num-product" type="number" name="num-product1" value="1" >
										<!--AJOUT QUANTITE
											<button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
												<i class="fs-12 fa fa-plus" aria-hidden="true"></i>
											</button> -->
										</div>
									</td>
									<td class="column-5"> <%= item.price %> €</td>
								</tr>
							<% total += item.price %>		
							<%end%>
						
						<%else%>
						<%= link_to "Créer un compte", new_user_registration_path%>	
					<%end%>
					

					</table>
				</div>
			</div>

			<div class="flex-w flex-sb-m p-t-25 p-b-25 bo8 p-l-35 p-r-60 p-lr-15-sm">
				<div class="flex-w flex-m w-full-sm">
					<div class="size11 bo4 m-r-10">
						<input class="sizefull s-text7 p-l-22 p-r-22" type="text" name="coupon-code" placeholder="Coupon Code">
					</div>

					
				</div>

			</div>

			<!-- Total -->
			<div class="bo9 w-size18 p-l-40 p-r-40 p-t-30 p-b-38 m-t-30 m-r-0 m-l-auto p-lr-15-sm">
				<h5 class="m-text20 p-b-24">
					Total Panier
				</h5>

				<!--SOUS TOTAL
				<div class="flex-w flex-sb-m p-b-12">
					<span class="s-text18 w-size19 w-full-sm">
						Sous-Total:
					</span>

					<span class="m-text21 w-size20 w-full-sm">
					<%= total %> €
				</div> -->

				<!-- SHIPPING 
				<div class="flex-w flex-sb bo10 p-t-15 p-b-20">
					<span class="s-text18 w-size19 w-full-sm">
						Envoi :
					</span>

					<div class="w-size20 w-full-sm">
						<p class="s-text8 p-b-23">
							There are no shipping methods available. Please double check your address, or contact us if you need any help.
						</p>

						<span class="s-text19">
							Calculate Shipping
						</span>

						<div class="rs2-select2 rs3-select2 rs4-select2 bo4 of-hidden w-size21 m-t-8 m-b-12">
							<select class="selection-2" name="country">
								<option>Select a country...</option>
								<option>US</option>
								<option>UK</option>
								<option>Japan</option>
							</select>
						</div>

						<div class="size13 bo4 m-b-12">
						<input class="sizefull s-text7 p-l-15 p-r-15" type="text" name="state" placeholder="State /  country">
						</div>

						<div class="size13 bo4 m-b-22">
							<input class="sizefull s-text7 p-l-15 p-r-15" type="text" name="postcode" placeholder="Postcode / Zip">
						</div>

						<div class="size14 trans-0-4 m-b-10">
							
							
							<!-- Button 
							<button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
								Update Totals
							</button>
						</div>
					</div>
				</div> -->

				<!--  -->
				<div class="flex-w flex-sb-m p-t-26 p-b-30">
					<span class="m-text22 w-size19 w-full-sm">
						Total:
					</span>

					<span class="m-text21 w-size20 w-full-sm">
					<!-- Permet le calcul du montant total -->
					<%= total %> €
					
					</span>
				</div>

				<div class="size15 trans-0-4">
					<!-- Button -->
				
						<%= link_to new_cart_path do%> 
						<button href="/carts/new" class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">Passer commande</button>
						<%end%>
	

				</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
	</div>

	<!-- Container Selection -->
	<div id="dropDownSelect1"></div>
	<div id="dropDownSelect2"></div>




	<script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});

		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect2')
		});
	</script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
	<%= render 'layouts/footer' %>
</html>

app/views/index/index.html.erb
<%= render 'layouts/navbar'%>
	<!-- Slide1 -->
	<section class="slide1">
		<div class="wrap-slick1">
			<div class="slick1">

				<div class="item-slick1 item1-slick1" style="background: url(images/banner-chat-5.jpg) no-repeat center fixed; background-size: cover;">

					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
						<h2 class="caption1-slide1 xl-text2 t-center bo14 p-b-6 animated visible-false m-b-22" data-appear="fadeInUp">
							Le chaton mignon 1
						</h2>

						<span class="caption2-slide1 m-text1 t-center animated visible-false m-b-33" data-appear="fadeInDown">
							New Collection 2018
						</span>

						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="zoomIn">
							<!-- Button -->
							
							<button class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4" onclick="scrollWin(0, 600)">Acheter</button>
						</div>
					</div>
				</div>

		<div class="item-slick1 item2-slick1" style="background: url(images/chat-banner-2.jpg) no-repeat center fixed; background-size: cover;">
					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
						<h2 class="caption1-slide1 xl-text2 t-center bo14 p-b-6 animated visible-false m-b-22" data-appear="rollIn">

							Chaton mignon 2

						</h2>

						<span class="caption2-slide1 m-text1 t-center animated visible-false m-b-33" data-appear="lightSpeedIn">
							New Collection 2018
						</span>

						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="slideInUp">
							<!-- Button -->
							<button class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4" onclick="scrollWin(0, 600)">Acheter</button>
						</div>
					</div>
				</div>

				<div class="item-slick1 item3-slick1" style="background: url(images/banner-chat-4.jpg) no-repeat center fixed; background-size: cover;">
					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
						<h2 class="caption1-slide1 xl-text2 t-center bo14 p-b-6 animated visible-false m-b-22" data-appear="rotateInDownLeft">

							Chaton mignon 3

						</h2>

						<span class="caption2-slide1 m-text1 t-center animated visible-false m-b-33" data-appear="rotateInUpRight">
							New Collection 2018
						</span>

						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="rotateIn">
							<!-- Button -->
							<button class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4" onclick="scrollWin(0, 600)">Acheter</button>
						</div>
					</div>
				</div>

			</div>
		</div>
	</section>


	<!-- Banner -->
	

	<!-- Our product -->
	<section class="bgwhite p-t-45 p-b-58">
		<div class="container">
			<div class="sec-title p-b-22">
				<h3 class="m-text5 t-center">
				   <span id="ancre"> Nos produits</span>
				</h3>
			</div>

     <!-- Tab panes -->
				
					<!-- - -->
					   


						<div class="row">

							   <% @items.each do |item| %>
					 

									<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
										<!-- Block2 -->
		 								
										<div class="block2">
											<div class="block2-img wrap-pic-w of-hidden pos-relative block2">
												<%if item.image_url != nil %>
													<%= image_tag('cats/' + item.image_url) %>  
												<%else%>
													<%= image_tag item.image %>
												<%end%>

												<div class="block2-overlay trans-0-4">

													<a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
														<i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
														<i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
													</a>
													<% if user_signed_in? %>
														<div class="block2-btn-addcart w-size1 trans-0-4">
														<!-- Button -->
														
															<%= link_to adding_path(item), method: 'post' do %> 
															<button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
																	Ajout panier
															</button>
															<%end%>
						
                    									<% else%>
														<div class="block2-btn-addcart w-size1 trans-0-4">

																	<%= link_to new_user_registration_path do %>
																	<button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
																	Connexion

															</button>
															<%end%>
                    									<%end%>
														
														
					
														
													</div>
												</div>
											</div>

											<div class="block2-txt p-t-20">
												<a href="product-detail.html" class="block2-name dis-block s-text3 p-b-5">

												
												</a>
												
												<%= item.title %><br><br>
												<%= item.description %><br><br>
												


												<span class="block2-price m-text6 p-r-5">
													<%= item.price%> €
												</span>
											</div>
										</div>
									</div>
							 <%end%>

				
					
							

</section>

<%= render 'layouts/footer'%>
			

									
							

							






	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
	</div>

	<!-- Container Selection1 -->
	<div id="dropDownSelect1"></div>

	<!-- Modal Video 01-->

<!--===============================================================================================-->
<!--===============================================================================================-->
<script>
function scrollWin(x, y) {
    window.scrollBy(x, y);
}
</script>
	<script type="text/javascript" src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="vendor/bootstrap/js/popper.js"></script>
	<script type="text/javascript" src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="vendor/select2/select2.min.js"></script>
	<script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
	</script>
<!--===============================================================================================-->
	<script type="text/javascript" src="vendor/slick/slick.min.js"></script>
	<script type="text/javascript" src="js/slick-custom.js"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="vendor/lightbox2/js/lightbox.min.js"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="vendor/sweetalert/sweetalert.min.js"></script>
	<script type="text/javascript">
		$('.block2-btn-addcart').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
			$(this).on('click', function(){
				swal(nameProduct, "ajouté au panier !", "success");
			});
		});

		$('.block2-btn-addwishlist').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");
			});
		});
	</script>

<!--===============================================================================================-->
	<script type="text/javascript" src="vendor/parallax100/parallax100.js"></script>
	<script type="text/javascript">
        $('.parallax100').parallax100();
	</script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>

app/views/index/upload.html.erb
<div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

<% if @item.image.attached? %>
<!-- @post.image.present? will always return true, use attached? to check presence -->
  <p>
    <strong>Image:</strong>
    <br>
    <%= image_tag @item.image %>
  </p>
<% end %>

app/views/layouts/_navbar.html.erb
	<header class="header2">
		<!-- Header desktop -->
		<div class="container-menu-header-v2 p-t-26">
			<div class="topbar2">
				<div class="topbar-social">
					<% if user_signed_in? %>							 
									<%= link_to profil_path do%> <%= current_user.email%> <%end%>
                    <% else%>
					<p> Bienvenue :D </p>
                    <%end%>
				</div>

				<!-- Logo2 -->
				<a href='<%=root_path%>' class="logo2">
					<%= image_tag("icons/logo_min.png", :alt => "MACHAT")%>
				</a>

				<div class="topbar-child2">
					<span class="topbar-email">
					</span>

					<% if user_signed_in? %>
                        <%= link_to destroy_user_session_path, method: "delete"  do %>Logout<%end%>
                    <% else%>
                        <%= link_to "Connexion", new_user_session_path %>
                        &nbsp
                        <%= link_to "S'enregistrer", new_user_registration_path %>
                    <%end%>
					
						
					</a>

					<span class="linedivide1"></span>

					<div class="header-wrapicon2 m-r-13">
						
						<%= image_tag("icons/icon-header-02.png", :alt => "panier", :class => "header-icon1 js-show-header-dropdown")%>
						<% if user_signed_in? && current_user.cart != nil %>
							<span class="header-icons-noti"><%=current_user.cart.items.size%></span>
						<%else%>
							<span class="header-icons-noti">0</span>
						<%end%>
<!--  ######################################## -->
<!-- Header cart noti -->
<!--  ######################################## -->		

						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
							<% if user_signed_in? && current_user.cart != nil %>
								<% total = 0 %> 
								<% current_user.cart.items.each do |item| %>
									<li class="header-cart-item">
										<div class="header-cart-item-img">
										<%if item.image_url != nil %>
													<%= image_tag('cats/' + item.image_url) %>  
										<%elsif item.image != nil%>
													<%= image_tag item.image%>
										<%end%> 
										</div>
										<div class="header-cart-item-txt">
											<a href="#" class="header-cart-item-name">
												<%=item.title%>
											</a>
											<span class="header-cart-item-info">
												<%=item.price%>€
											</span>
											<span>
											<%= link_to remove_path(item), method: 'post' do %> Supprimer <%end%>
											</span>
										</div>
									</li>
									<% total += item.price%> 
								<%end%>
								

							
							<%else%>
									<li class="header-cart-item">
										<div class="header-cart-item-img">
											
										</div>

										<div class="header-cart-item-txt">
											<a href="#" class="header-cart-item-name">
												AUCUN ITEM DANS LE PANIER :(
											</a>

											<span class="header-cart-item-info">
												
											</span>
										</div>
									</li>

							<%end%>
							</ul>
						<% if user_signed_in? && current_user.cart != nil %>
							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									
									<%=link_to "Panier", cart_path, class:"flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4"%></a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<%= link_to "Check Out", new_cart_path, class: "flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4" %>
								</div>
							</div>
							<div class="header-cart-total">
								<%= total %>€
							</div>
						<%end%>
							

						<div class="header-cart-total">
								
						</div>

						<div class="header-cart-buttons">
							<div class="header-cart-wrapbtn">
									
								
							</div>
							<div class="header-cart-wrapbtn">
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
		

<!--  ######################################## -->
<!-- Header cart noti -->
<!--  ######################################## -->
			<div class="wrap_header">

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							<li>
								<%=link_to "Accueil", root_path%>
							</li>

							
						<% if user_signed_in? %>
							<li>
								<%=link_to "Panier", cart_path%>
							</li>
							<li>
								<%=link_to "Création items admin", new_item_path%>
							</li>
							<li>
								<%=link_to "Tous les items admin", items_path%>
							</li>
						<% end %>
						</ul>
					</nav>
				</div>

				<!-- Header Icon -->
				<div class="header-icons">

				</div>
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="<%root_path%>" class="logo-mobile">
				<img src="images/icons/logo.png" alt="IMG-LOGO">
			</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="images/icons/icon-header-01.png" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide2"></span>

					<div class="header-wrapicon2">
						<%= image_tag("icons/icon-header-02.png", :alt => "panier", :class => "header-icon1 js-show-header-dropdown")%>
						<span class="header-icons-noti">0</span>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="images/item-cart-01.jpg" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											White Shirt With Pleat Detail Back
										</a>

										<span class="header-cart-item-info">
											1 x $19.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="images/item-cart-02.jpg" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Converse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="images/item-cart-03.jpg" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								Total: $75.00
							</div>

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1">
							Free shipping for standard order over $100
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								<% if user_signed_in? %>
									<%= link_to destroy_user_session_path, method: "delete"  do %>Logout<%end%> 
                    			<% else%>
									<%= link_to "Log in", new_user_session_path %>
									&nbsp
									<%= link_to "Sign up", new_user_registration_path %>
                    			<%end%>
							</span>

							
						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="<%root_path%>">Home</a>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>

					

					<li class="item-menu-mobile">
						<a href="product.html">Sale</a>
					</li>

					<li class="item-menu-mobile">
						<a href="cart.html">Features</a>
					</li>

					<li class="item-menu-mobile">
						<a href="blog.html">Blog</a>
					</li>

					<li class="item-menu-mobile">
						<a href="about.html">About</a>
					</li>

					<li class="item-menu-mobile">
						<a href="contact.html">Contact</a>
					</li>
				</ul>
			</nav>
		</div>
	</header>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>