config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  get 'profil', to: 'profil#profil'
  resources :items
  resources :item_adds
  root 'index#index'
  get 'upload', to: 'index#upload', as: 'upload'
  get 'cart', to: 'index#cart', as: 'cart'
  post '/panier/remove/:id', to: "index#rm_from_cart", as: :remove
  get '/panier/remove/:id', to: "index#rm_from_cart", as: :removed
  post '/panier/:id', to: "index#add_to_cart", as: :adding
  devise_for :users

  resources :carts, only: [:new]
  get 'show', to: 'carts#show', as: 'pay'
  resources :charges

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bridge.rb
class Bridge < ApplicationRecord
  	belongs_to :cart
  	belongs_to :item
end

app/models/cart.rb
class Cart < ApplicationRecord

	has_many :bridges
	has_many :items, through: :bridges
	has_one :user
end

app/models/command.rb
class Command < ApplicationRecord
	belongs_to :user
	has_many :command_items
	has_many :items, through: :command_items
end

app/models/command_item.rb
class CommandItem < ApplicationRecord
	belongs_to :command
	belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :bridges
	has_many :carts, through: :bridges
	has_many :command_items 
	has_many :commands, through: :command_items
	has_one_attached :image
end

app/models/item_add.rb
class ItemAdd < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord

	has_one :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :cart
  has_many :commands

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def new

  end



  def show

    item = current_user.cart.items.all
    # Récupérer ts les items dans le panier du current user
  end

  def add_item_to_order
    ord = Order.new
    ord.user = current_user
    ord.save
    com = Command.new
    com.user = current_user

    current_user.cart.items.each do | item |
      com.items << item
      OrderMailer.with(order: @order).user_order_mailer.deliver_now
      OrderMailer.with(order: @order).admin_order_mailer.deliver_now
    end
    com.save
    current_user.cart.items.clear

    redirect_to root_path
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :authenticate_user!, only: [:cart]
  def index

    @items = Item.all

  end

  def cart
  end

  def add_to_cart
    if current_user.cart == nil
      current_user.create_cart
    end
    item = Item.find(params[:id])
    current_user.cart.items << item
    p current_user.cart.items
    puts '__________________'
    sleep 0.4 
    redirect_to root_path
  end 

  def rm_from_cart

    item_id = params[:id]
    cart_id = current_user.cart.id
    bridge = Bridge.where("cart_id == #{cart_id} AND item_id == #{item_id} ").first
    bridge.destroy
    redirect_to root_path

  end 

  def rm_from_cart_page

    item_id = params[:id]
    cart_id = current_user.cart.id
    bridge = Bridge.where("cart_id == #{cart_id} AND item_id == #{item_id} ").first
    bridge.destroy
    redirect_to root_path

  end 

  def upload
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
        puts '--------'
        p params
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :image )
      
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController
  def profil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).order_mail.deliver_now
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/item_adds_helper.rb
module ItemAddsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/views/carts/new.html.erb
<%= render 'layouts/navbar'%>
<div class="container-table-cart pos-relative">
				<div class="wrap-table-shopping-cart bgwhite">
					<table class="table-shopping-cart">
						<tr class="table-head">
							<th class="column-1 title-table-cart"></th>
							<th class="column-2 title-table-cart">Produit</th>
							<th class="column-3 title-table-cart">Prix</th>
							<th class="column-4 title-table-cart"></th>
						
						</tr>
<% total =0 %>
<% current_user.cart.items.each do |item| %>
						<tr class="table-row">
									<td class="column-1">
										<div class="cart-img-product b-rad-4 o-f-hidden">
											<%if item.image_url != nil %>
													<%= image_tag('cats/' + item.image_url) %>  
												<%else%>
													<%= image_tag item.image%>
												<%end%>
										
									</td>
									<td class="column-2"><%= item.title %></td>
									<td class="column-3"> <%= item.price %>€</td>
									<td class="column-4">
											<%= link_to remove_path(item), method: 'post' do %> Supprimer <%end%>
											</td>
										<div class="flex-w bo5 of-hidden w-size17">
<% total += item.price %>

<%end%>									</div>
									</td>
										</div>

						</tr>
					</table>
				</div>
</div>

<section>
<div class="bo9 w-size18 p-l-40 p-r-40 p-t-30 p-b-38 m-t-30 m-r-0 m-l-auto p-lr-15-sm">
				<h5 class="m-text20 p-b-24">
					Total à régler
				</h5>
<div class="flex-w flex-sb-m p-t-26 p-b-30">
					<span class="m-text22 w-size19 w-full-sm">
						Total:
					</span>

					<span class="m-text21 w-size20 w-full-sm">
					<!-- Permet le calcul du montant total -->
					<%= total %> €
					
					</span>
				</div>

				<div class="size15 trans-0-4">
					<!-- Button -->
<%= form_tag charges_path do %>
				
<% tag.article data: { user_id: current_user } %>


    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <%end%>


   

  
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" 
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description= "<%= total%> €"
          data-amount="<%= a = total * 100 %> "
          data-locale= "<%current_user%>"
          </script>

          <% end %>

				
				</div>
			</div>
		</div>
	</section>
	<%= render 'layouts/footer'%>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit "Créer", class: 'btn_login' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<button class="btn-back"><a href=<%=root_path%>>⇦ Vers l'accueil</a></button>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= item.image_url %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<%= image_tag("form_bckg.png", :alt => "background chaton", :class => "show_form_bckg")%>
<button class="btn-back"><a href=<%=root_path%>>⇦ Vers l'accueil</a></button>
  <div id="user_form">
<h1>New Item</h1>

<%= render 'form', item: @item %>


<%= link_to 'Back', items_path %>

  </div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag("form_bckg.png", :alt => "background chaton", :class => "show_form_bckg")%>
<button class="btn-back"><a href=<%=root_path%>>⇦ Vers l'accueil</a></button>
  <div id="user_form">
  
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>



<% if @item.image.attached? %>
  <p>
    <strong>Image:</strong>
    <br>
   <%= image_tag @item.image, :style => "width:60%" %></div>
  </p>
<% end %>
<p style=" text-align: center;
    margin-top: -60px;">
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %></p>
</div>